AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Team Dashboard Backend - Serverless backend for team workload visibility application

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: java17
    Environment:
      Variables:
        SPRING_PROFILES_ACTIVE: lambda,dynamodb
        JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djava.awt.headless=true"

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment (dev/staging/prod)

Resources:
  TeamDashboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'team-dashboard-v2-${Environment}'
      CodeUri: backend/
      Handler: com.teamdashboard.SimpleLambdaHandler::handleRequest
      Description: Team Dashboard API Lambda function
      Environment:
        Variables:
          WORKLOAD_STATUS_TABLE: !Ref WorkloadStatusTable
          TEAM_ISSUE_TABLE: !Ref TeamIssueTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref TeamDashboardApi
        RootApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref TeamDashboardApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WorkloadStatusTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamIssueTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

  TeamDashboardApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'team-dashboard-v2-${Environment}'
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  WorkloadStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'WorkloadStatus-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: TeamDashboard
        - Key: Component
          Value: WorkloadStatus

  TeamIssueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'TeamIssue-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: issueId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: issueId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: TeamDashboard
        - Key: Component
          Value: TeamIssue

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${TeamDashboardApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"
  
  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref TeamDashboardFunction
    Export:
      Name: !Sub "${AWS::StackName}-FunctionName"
  
  WorkloadStatusTableName:
    Description: "WorkloadStatus DynamoDB Table Name"
    Value: !Ref WorkloadStatusTable
    Export:
      Name: !Sub "${AWS::StackName}-WorkloadStatusTable"
  
  TeamIssueTableName:
    Description: "TeamIssue DynamoDB Table Name"
    Value: !Ref TeamIssueTable
    Export:
      Name: !Sub "${AWS::StackName}-TeamIssueTable"