spring:
  profiles:
    active: local
  
  application:
    name: team-dashboard-local
  
  datasource:
    url: jdbc:h2:mem:team_dashboard
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8081
  address: 0.0.0.0

logging:
  level:
    com.teamdashboard: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web: DEBUG