spring:
  application:
    name: team-dashboard
  
  datasource:
    url: jdbc:h2:mem:team_dashboard
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    com.teamdashboard: DEBUG