spring:
  application:
    name: team-dashboard
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/team_dashboard}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /api

logging:
  level:
    com.teamdashboard: INFO
    org.springframework.security: WARN